grpc:
  listen_addr: ":50051"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  key: "voting:topics"

vote:
  topics:
    - "Golang"
    - "Kubernetes"
    - "Rust"

server:
  request_timeout: "3s"

logging:
  level: "info"
